### ISSUE TITLE
a bug: 2D + pair_chain_feature

### ISSUE THREAD

**Issue by LilySnow** [DeepRank/deeprank#3] opened 2018-03-01 15:05 UTC
The code crashes when I use 2D convolution with pair_chain_feature. 

**Error message:** 

Traceback (most recent call last):
  File "learn_2d.py", line 35, in <module>
    model.train(nepoch = 1,train_batch_size = 2,num_workers=8,divide_trainset=[0.8,0.2])
  File "/home/lixue/deeprank/BM4/xper/all/exp001/deeprank/deeprank/learn/NeuralNet.py", line 276, in train
    num_workers=num_workers)
  File "/home/lixue/deeprank/BM4/xper/all/exp001/deeprank/deeprank/learn/NeuralNet.py", line 456, in _train
    self.valid_loss,self.data['valid'] = self._epoch(valid_loader,train_model=False)
  File "/home/lixue/deeprank/BM4/xper/all/exp001/deeprank/deeprank/learn/NeuralNet.py", line 537, in _epoch
    outputs = self.net(inputs)
  File "/home/lixue/softwares/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lixue/deeprank/BM4/xper/all/exp001/model2d.py", line 55, in forward
    x = self._forward_features(x)
  File "/home/lixue/deeprank/BM4/xper/all/exp001/model2d.py", line 47, in _forward_features
    x = F.relu(self.convlayer2D_000(x))
  File "/home/lixue/softwares/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lixue/softwares/anaconda3/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 254, in forward
    self.padding, self.dilation, self.groups)
  File "/home/lixue/softwares/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py", line 52, in conv2d
    return f(input, weight, bias)
RuntimeError: Need input.size[1] == 30 but got 1 instead.

**Part of my code:**

data_set = DataSet(train_files,
                test_database = test_database,
                grid_shape = (30,30,30),
                  # select_feature= 'all',
                select_feature = {'Feature_ind' : ['pssm_ic']},
                pair_chain_feature=np.add,
                select_target='DOCKQ',
                dict_filter = {'DOCKQ':'>0.1'},
                normalize_features=True,normalize_targets=True,tqdm=False)

**My code location**: /home/lixue/deeprank/BM4/xper/all/exp001/learn_2d.py

**Comment by LilySnow** [comment] 2018-03-02 08:14
And the output also has some undesired lines:

>    Checking dataset Integrity
>    Processing data set
>    Train dataset
>    Test dataset
> **[0, 1]**
>    Normalization factor :

....

> : epoch 000 / 001 ---------------------------------------------
> [0, 1]
> [0, 1]
> [0, 1]

**Comment by NicoRenaud** [comment] 2018-03-02 09:35
I've fixed that and added a feature check
I think the issue is that you had Feature_sum specified in select_feature ?
I've modified notravis_test_learn2D.py so that it actually works :)

**Comment by NicoRenaud** [comment] 2018-03-06 15:42
I'm closing the issue since it was fixed

**Closed by NicoRenaud** 2018-03-06 15:42 UTC
